---
- file:
   path: "{{ kvm_image_root }}/{{ kvm_machine.name }}/conf.d"
   state: directory
   owner: root
   group: root
   mode: "0750"
- template:
   dest: "{{ kvm_image_root }}/{{ kvm_machine.name }}/{{ kvm_machine.name }}-start.sh"
   src: templates/qemu-start.sh.j2
   owner: "{{ kvm_machine.name }}"
   group: "{{ kvm_machine.name }}"
   mode: "0755"
- template:
   dest: "{{ kvm_image_root }}/{{ kvm_machine.name }}/{{ kvm_machine.name }}-stop.sh"
   src: templates/qemu-stop.sh.j2
   owner: "{{ kvm_machine.name }}"
   group: "{{ kvm_machine.name }}"
   mode: "0755"
- template:
   dest: "{{ kvm_image_root }}/{{ kvm_machine.name }}/{{ kvm_machine.name }}-monitor.sh"
   src: templates/qemu-monitor.sh.j2
   owner: "{{ kvm_machine.name }}"
   group: "{{ kvm_machine.name }}"
   mode: "0755"
- template:
   dest: "{{ kvm_image_root }}/{{ kvm_machine.name }}/{{ kvm_machine.name }}.conf"
   src: templates/qemu.conf.j2
   owner: "{{ kvm_machine.name }}"
   group: "{{ kvm_machine.name }}"
   mode: "0640"
- template:
   dest: "{{ kvm_image_root }}/{{ kvm_machine.name }}/conf.d/etc-hostname"
   src: templates/etc-hostname.j2
   owner: root
   group: root
   mode: "0644"
- template:
   dest: "{{ kvm_image_root }}/{{ kvm_machine.name }}/conf.d/root-.ssh-authorized_keys"
   src: templates/root-.ssh-authorized_keys.j2
   owner: root
   group: root
   mode: "0644"
- template:
   dest: "{{ kvm_image_root }}/{{ kvm_machine.name }}/conf.d/etc-network-interfaces"
   src: templates/etc-network-interfaces.j2
   owner: root
   group: root
   mode: "0644"
- template:
   dest: "{{ kvm_image_root }}/{{ kvm_machine.name }}/conf.d/etc-acpi-events-powerbtn"
   src: templates/etc-acpi-events-powerbtn.j2
   owner: root
   group: root
   mode: "0644"
- template:
   dest: "{{ kvm_image_root }}/{{ kvm_machine.name }}/conf.d/etc-acpi-powerbtn.sh"
   src: templates/etc-acpi-powerbtn.sh.j2
   owner: root
   group: root
   mode: "0755"
- template:
   dest: "{{ kvm_image_root }}/{{ kvm_machine.name }}/{{ kvm_machine.name }}-create-image.sh"
   src: templates/create-image.sh.j2
   owner: root
   group: root
   mode: "0700"
- copy:
   dest: "{{ kvm_image_root }}/{{ kvm_machine.name }}/{{ kvm_machine.name }}.status.enabled"
   content: ""
   owner: "{{ kvm_machine.name }}"
   group: "{{ kvm_machine.name }}"
   mode: "0444"
- template:
   dest: "/etc/systemd/system/vm-{{ kvm_machine.name }}-image.service"
   src: templates/vm-systemd-image.service.j2
   owner: root
   group: root
   mode: "0644"
- template:
   dest: "/etc/systemd/system/vm-{{ kvm_machine.name }}-qemu.service"
   src: templates/vm-systemd-qemu.service.j2
   owner: root
   group: root
   mode: "0644"
- template:
   dest: "/etc/systemd/system/vm-{{ kvm_machine.name }}.service"
   src: templates/vm-systemd.service.j2
   owner: root
   group: root
   mode: "0644"
- systemd:
   enabled: yes
   state: started
   daemon_reload: yes
   name: vm-{{ kvm_machine.name }}

