---
# test if kvm machine needs to be set up or shut down here
- name: uid machine name checksum
  set_fact:
    kvm_machine_tmp_chks: "{{ kvm_machine.name|checksum }}"
- name: calc chkb and chkd
  set_fact:
    kvm_machine_tmp_chkb: "{{ ((kvm_machine_tmp_chks[5:6]|int(0, 16)/3.2)+1)|int|string }}"
    kvm_machine_tmp_chkd: "{{ kvm_machine_tmp_chks[0:4]|int(0, 16)|string }}"
- name: calculate new uid and set set spice password
  set_fact:
    kvm_machine_uid: "{{ kvm_machine.uid|default([kvm_machine_tmp_chkb[0:1], '0000']|join|int + kvm_machine_tmp_chkd[-4:]|int) }}"
    kvm_machine_spice_password: "{{ kvm_spice_passwords[kvm_machine.name]|default(kvm_default_spice_password|default('ToLazyToConfigureASpicePassword')) }}"
    kvm_machine_spice_addr: "{{ kvm_machine.spice_addr|default(kvm_default_spice_addr|default('::1')) }}"
    kvm_machine_spice_port: "{{ kvm_machine.spice_port|default(kvm_machine.uid|default([kvm_machine_tmp_chkb[0:1], '0000']|join|int + kvm_machine_tmp_chkd[-4:]|int)) }}"
    kvm_machine_firmware_type: "{{ kvm_machine.firmware|default(kvm_images[kvm_machine.image][kvm_machine.image_version]['firmware']|default(kvm_default_firmware)) }}"
    kvm_machine_accel_cur: "{{ kvm_machine.accel|default(kvm_machine_accel[kvm_machine.name]|default(kvm_default_accel|default('kvm'))) }}"
- fail:
    msg: |
      Uid {{ kvm_machine_uid }} is not unique or Name {{ kvm_machine.name }} is not unique. 
      If two hostnames lead to the same uid try defining a different uid in the machine config.
  when: kvm_machine_uid in kvm_unique_uid or kvm_machine.name in kvm_unique_name
- name: set unique values
  set_fact: 
    kvm_unique_uid: "{{ kvm_unique_uid }} {{ kvm_machine_uid }}={{ kvm_machine.name }}"
    kvm_unique_name: "{{ kvm_unique_name }} {{ kvm_machine.name }}={{ kvm_machine_uid }}"
- include_tasks: host_unknown.yml
  when: "inventory_hostname not in kvm_machine.deploy_to"
- include_tasks: exterminate_kvm_machine.yml
  vars:
    kvm_machine_name: "{{ kvm_machine.name }}"
  when: kvm_machine.deploy_to[inventory_hostname] == "drop" or kvm_machine.deploy_to[inventory_hostname] == "exterminate"
- include_tasks: kvm_machine_create.yml
  when: kvm_machine.deploy_to[inventory_hostname] == "start"
