---
# test if kvm machine needs to be set up or shut down here
- name: uid machine name checksum
  set_fact:
    kvm_machine_tmp_chks: "{{ kvm_machine.name|checksum }}"
- name: calc chkb and chkd
  set_fact:
    kvm_machine_tmp_chkb: "{{ ((kvm_machine_tmp_chks[5:6]|int(0, 16)/3.2)+1)|int|string }}"
    kvm_machine_tmp_chkd: "{{ kvm_machine_tmp_chks[0:4]|int(0, 16)|string }}"
- debug:
    msg: |
      set default env and uid for {{ kvm_machine.name }} {{ kvm_machine.image }} {{ kvm_machine.image_version }}  
- name: set default env and uid for {{ kvm_machine.name }} {{ kvm_machine.image }} {{ kvm_machine.image_version }} 
  set_fact:
    kvm_machine_uid: "{{ kvm_machine.uid|default([kvm_machine_tmp_chkb[0:1], '0000']|join|int + kvm_machine_tmp_chkd[-4:]|int) }}"
    kvm_machine_spice_password: "{{ kvm_spice_passwords[kvm_machine.name]|default(kvm_default_spice_password|default('ToLazyToConfigureASpicePassword')) }}"
    kvm_machine_spice_unix_access: "{{ kvm_machine.spice_unix_access|default(kvm_default_spice_unix_access|default(False)) }}"
    kvm_machine_spice_unix: "{{ kvm_machine.spice_unix|default(kvm_default_spice_unix|default(False)) }}"
    kvm_machine_spice_disable_ticketing: "{{ kvm_machine.spice_disable_ticketing|default(kvm_default_spice_disable_ticketing|default(False)) }}"
    kvm_machine_spice_disable_agent_file_xfer: "{{ kvm_machine.spice_disable_agent_file_xfer|default(kvm_default_spice_disable_agent_file_xfer|default(True)) }}"
    kvm_machine_spice_disable_copy_paste: "{{ kvm_machine.spice_disable_copy_paste|default(kvm_default_spice_disable_copy_paste|default(True)) }}"
    kvm_machine_spice_addr: "{{ kvm_machine.spice_addr|default(kvm_default_spice_addr|default('::1')) }}"
    kvm_machine_spice_port: "{{ kvm_machine.spice_port|default(kvm_machine.uid|default([kvm_machine_tmp_chkb[0:1], '0000']|join|int + kvm_machine_tmp_chkd[-4:]|int)) }}"
    kvm_machine_spice_tls: "{{ kvm_machine.spice_tls|default(kvm_spice_tls|default(True)) }}"
    kvm_machine_spice_x509_dir: "{{ kvm_machine.x509_dir|default([kvm_image_root, '/', kvm_machine.name, '/ssl']|join()) }}"
    kvm_machine_spice_x509_key_file: "{{ kvm_machine.x509_key_file|default('privkey.pem') }}"
    kvm_machine_spice_x509_cert_file: "{{ kvm_machine.x509_cert_file|default('cert.pem') }}"
    kvm_machine_spice_x509_cacert_file: "{{ kvm_machine.x509_cacert_file|default('fullchain.pem') }}"
    kvm_machine_spice_x509_dh_key_file: "{{ kvm_machine.x509_dh_key_file|default('none') }}"
    kvm_machine_soundhw: "{{ kvm_machine.soundhw|default(kvm_default_soundhw|default(False)) }}"
    kvm_machine_ext_ports: "{{ kvm_machine.ext_ports|default(kvm_machine_default_ext_ports|default({})) }}"
    kvm_machine_firmware_type: "{{ kvm_machine.firmware|default(kvm_images[kvm_machine.image][kvm_machine.image_version]['firmware']|default(kvm_default_firmware)) }}"
    kvm_machine_accel_cur: "{{ kvm_machine.accel|default(kvm_machine_accel[kvm_machine.name]|default(kvm_default_accel|default('kvm'))) }}"
    kvm_machine_drive_if: "{{ kvm_machine.drive_if|default(kvm_default_drive_if|default('virtio')) }}"
    kvm_machine_graphics: "{{ kvm_machine.graphics|default(kvm_default_graphics|default(False)) }}"
    kvm_machine_admin_port: "{{ kvm_machine.admin_port|default(kvm_images[kvm_machine.image][kvm_machine.image_version]['admin_port']|default(kvm_default_admin_port|default('22'))) }}"
- fail:
    msg: |
      The Name {{ kvm_machine.name }} is not unique, try a different one. 
  when: kvm_machine.name in kvm_unique_name
- fail:
    msg: |
      Uid {{ item }} is not unique 
      every machine needs a space of +5 uids, to get free tcp ports to patch admin services to the VM. 
      If two hostnames lead to the same uid try defining a different uid in the machine config.
      The current uid of this vm would have been {{ kvm_machine_uid }} which is already been taken by 
      {{ kvm_unique_uid[item] }}
  when: item in kvm_unique_uid
  with_items: 
    - "{{ kvm_machine_uid }}"
    - "{{ kvm_machine_uid|int(0, 10)+1 }}"
    - "{{ kvm_machine_uid|int(0, 10)+2 }}"
    - "{{ kvm_machine_uid|int(0, 10)+3 }}"
    - "{{ kvm_machine_uid|int(0, 10)+4 }}"
    - "{{ kvm_machine_uid|int(0, 10)+5 }}"
- name: set unique name
  set_fact: 
    kvm_unique_name: "{{ kvm_unique_name }} {{ kvm_machine.name }}={{ kvm_machine_uid }}"
- name: set unique uid values
  set_fact: 
    kvm_unique_uid: "{{ kvm_unique_uid }} {{ item }}={{ kvm_machine.name }}"
  with_items: 
    - "{{ kvm_machine_uid }}"
    - "{{ kvm_machine_uid|int(0, 10)+1 }}"
    - "{{ kvm_machine_uid|int(0, 10)+2 }}"
    - "{{ kvm_machine_uid|int(0, 10)+3 }}"
    - "{{ kvm_machine_uid|int(0, 10)+4 }}"
    - "{{ kvm_machine_uid|int(0, 10)+5 }}"
- include_tasks: host_unknown.yml
  when: "inventory_hostname not in kvm_machine.deploy_to"
- include_tasks: exterminate_kvm_machine.yml
  vars:
    kvm_machine_name: "{{ kvm_machine.name }}"
  when: kvm_machine.deploy_to[inventory_hostname]["exterminate"] == 1 or  kvm_machine.deploy_to[inventory_hostname]["reinstall"] == 1 
- include_tasks: kvm_machine_create.yml
  when: kvm_machine.deploy_to[inventory_hostname]['setup'] == 1
