---
- file:
   dest: "{{ kvm_image_downloads }}"
   state: directory
   owner: "root"
   group: "root"
   mode: "0750"
- name: "Download {{ kvm_image_name }} version {{ kvm_image_version }}"
  get_url:
    tmp_dest: "{{ kvm_image_downloads }}/"
    url: "{{ kvm_images[kvm_image_name][kvm_image_version]['url'] }}"
    checksum: "{{ kvm_images[kvm_image_name][kvm_image_version]['chksum'] }}"
    dest: "{{ kvm_image_downloads }}/{{ kvm_image_name }}.{{ kvm_image_version }}.gz"
    mode: 0444
- name: load image to pool
  shell: |
     zfs list "{{ kvm_image_zpool }}/{{ kvm_image_name }}@{{ kvm_image_version }}" 
     if [[ $? != 0 ]] 
     then
       pigz -d -c "{{ kvm_image_downloads }}/{{ kvm_image_name }}.{{ kvm_image_version }}.gz" | 
       zfs receive "{{ kvm_image_zpool }}/{{ kvm_image_name }}" && exit 42 || exit $?
     fi
     exit 0
  args:
    executable: /bin/bash
  register: zfs_load_image_result
  failed_when: "zfs_load_image_result.rc != 42 and zfs_load_image_result.rc != 0"
  changed_when: "zfs_load_image_result.rc == 42"
