---
# tasks file for conesphere.kvm.manager
- apt: 
    name: "{{ item }}"
    state: latest
  with_items:
    - qemu-kvm
    - pigz
    - parted
    - util-linux
    - socat
    - ovmf
    - dosfstools
- import_tasks: setup_nat64.yml

