---
# tasks file for conesphere.kvm.manager
- apt: 
    name: "{{ item }}"
    state: latest
  with_items:
    - qemu-kvm
    - pigz
    - parted
    - util-linux
    - socat
    - ovmf
    - dosfstools
- import_tasks: setup_nat64.yml
- file:
   dest: /usr/local/bin
   state: directory
   owner: root
   group: root
   mode: "0755"
- name: create exports directory for zfs transmission 
  file:
   dest: /etc/zfs-pull-exports
   state: directory
   owner: root
   group: root
   mode: "0755"
- name: copy zfs transfer tools
  copy:
   src: "files/zfspull/{{ item }}"
   dest: "/usr/local/bin/{{ item }}"
   owner: root
   group: root
   mode: "0755"
  with_items:
    - zfs-pull.sh
    - zfs-pull-server.sh
    - zfs-pull-server-sshcmd.sh
- template:
   dest: /usr/local/bin/fdisk_max_partition.sh
   src: templates/fdisk_max_partition.sh.j2
   owner: root
   group: root
   mode: "0755"
- template:
   dest: /usr/local/bin/fdisk_max_partition_gpt.sh
   src: templates/fdisk_max_partition_gpt.sh.j2
   owner: root
   group: root
   mode: "0755"
- file:
   dest: "/etc/qemu"
   state: directory
   owner: root
   group: root
   mode: "0755"
- template:
   dest: /etc/qemu/bridge.conf
   src: templates/etc-qemu-bridge.conf.j2
   owner: root
   group: root
   mode: "0444"
- file:
   dest: "/usr/lib/qemu"
   state: directory
   owner: root
   group: kvm
   mode: "0750"
- file:
   dest: "/usr/lib/qemu/qemu-bridge-helper"
   state: file
   owner: root
   group: root
   mode: "4755"
- template:
   dest: /etc/udev/rules.d/kvm_sphere_zvol_permissions.rules
   src: templates/etc-udev-rules.d-kvm_sphere_zvol_permissions.rules.j2
   owner: root
   group: root
   mode: "0644"
  register: udev_zvol_permissions
- service:
    name: udev
    state: restarted
  when: udev_zvol_permissions.changed
- file:
   dest: "{{ kvm_firmware_root }}"
   state: directory
   owner: "root"
   group: "root"
   mode: "0755"
- name: "Download {{ kvm_firmware_cur.key }}"
  get_url:
    url: "{{ kvm_firmware_cur.value.url }}"
    checksum: "{{ kvm_firmware_cur.value.chksum }}"
    dest: "{{ kvm_firmware_root }}/{{ kvm_firmware_cur.key }}.firmware"
    mode: 0444
  with_dict: "{{ kvm_firmware }}"
  loop_control:
    loop_var: kvm_firmware_cur
- include_tasks: exterminate_kvm_machine.yml
  with_items: "{{ kvm_machine_exterminate }}"
  loop_control:
    loop_var: kvm_machine_name
- include_tasks: kvm_machine.yml
  with_items: "{{ kvm_machines }}"
  loop_control:
    loop_var: kvm_machine

