---
- import_tasks: kvm_sphere_setup.yml
  when: mode == "system"
- import_tasks: exterminate_kvm_machine.yml
  when: mode == "exterminate"
- import_tasks: kvm_machine.yml
  when: mode == "machine"
- import_tasks: kvm_machine_backup.yml
  when: mode == "backup"
- import_tasks: kvm_machine_start.yml
  when: mode == "start"
- import_tasks: kvm_machine_stop.yml
  when: mode == "stop"

